name: Release Chrome Extension

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install CRX packaging tool
        run: npm install -g crx3

      - name: Prepare dist folder
        run: |
          mkdir -p dist
          cp -r background.js popup.js popup.html options.html options.js manifest.json icons dist/ 2>/dev/null || true

      - name: Create ZIP archive
        run: |
          cd dist
          zip -r ../chrome-extension.zip .
          cd ..

      - name: Create CRX package
        env:
          EXT_KEY: ${{ secrets.EXTENSION_KEY_PEM }}
        run: |
          echo "$EXT_KEY" > extension.pem
          npx crx3 dist --key extension.pem --crx chrome-extension.crx
          rm extension.pem

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            chrome-extension.zip
            chrome-extension.crx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
